GRANT EXECUTE PROCEDURE ON SYSUIF.REMOVE_FILE TO dbc;
GRANT EXECUTE PROCEDURE ON SYSUIF.REPLACE_FILE TO dbc;
GRANT EXECUTE PROCEDURE ON SYSUIF.INSTALL_FILE TO dbc;
GRANT SELECT ON demo TO dbc;
GRANT DROP PROCEDURE ON demo TO dbc;
GRANT CREATE EXTERNAL PROCEDURE ON demo TO dbc;